version: '3.1'
networks:
  app_network:
    driver: bridge

services:
  puppeteer-service:
    build:
      context: .
      dockerfile: ./env/Dockerfile.puppeteer
    ports:
      - 3002:3002
    networks:
      - app_network
    volumes:
      - ./feature/puppeteer:/app
    # restart: always
  cc-service:
    build:
      context: .
      dockerfile: ./env/Dockerfile.server
    ports:
      - 3000-3001:3000-3001
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    networks:
      - app_network
    # restart: always
  # cc-fe:
  #   build:
  #     context: .
  #     dockerfile: ./env/Dockerfile.web
  #   ports:
  #     - 3003:3003
  #   volumes:
  #     - ./frontend:/app
  #   env_file:
  #     - .env
  #   networks:
  #     - app_network
