version: '3.1'
services:
  cc-service:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3000-3003:3000-3003
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
    restart: always
    privileged: true
networks:
  app_network:
    driver: bridge
