version: '3.1'
networks:
  app_network:
    driver: bridge

services:
  puppeteer-service:
    build:
      context: ./feature/puppeteer
      dockerfile: ./Dockerfile
    ports:
      - 3002:3002
    networks:
      - app_network
    # restart: always
  cc-service:
    build:
      context: ./
      dockerfile: ./docker/production/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
    restart: always
