version: '3.1'
services:
  cc-service:
    build:
      context: ./
      dockerfile: ./docker/production/Dockerfile
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
    restart: always
networks:
  app_network:
    driver: bridge
