version: '3'
services:
  cc-service:
    build: .
    ports:
      - 3001:3001
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
