version: '3.1'
networks:
  app_network:
    driver: bridge

services:
  puppeteer-service:
    build:
      context: ./feature/puppeteer
      dockerfile: ./Dockerfile
    ports:
      - 3002:3002
    networks:
      - app_network
    # restart: always
  cc-service:
    build:
      context: ./
      dockerfile: ./docker/development/Dockerfile
    ports:
      - 3000-3001:3000-3001
    volumes:
      - ./server:/app/server
    env_file:
      - .env
    environment:
      - WATCHFILES_FORCE_POLLING=true
    links:
      - puppeteer-service:puppeteer
    networks:
      - app_network
    # restart: always
  cc-fe:
    build:
      context: ./
      dockerfile: ./docker/development/Dockerfile.FE
    ports:
      - 3003:3003
    volumes:
      - .:/app
      - /node_modules
    env_file:
      - .env
    depends_on:
      - puppeteer-service
      - cc-service
    networks:
      - app_network
    # restart: always
