const CC_TYPE = {
  UPDATE_GIATRIGOPVON: 'UPDATE_GIATRIGOPVON',
  UPDATE_THANHVIENGOPVON: 'UPDATE_THANHVIENGOPVON',
  UPDATE_NGUOIDAIDIEN: 'UPDATE_NGUOIDAIDIEN',
  UPDATE_DIACHITRUSOCHINH: 'UPDATE_DIACHITRUSOCHINH',
  UPDATE_TENCONGTY: 'UPDATE_TENCONGTY',
  UPDATE_NGANHNGHEDANGKI: 'UPDATE_NGANHNGHEDANGKI',
  UPDATE_FORM: 'UPDATE_FORM',
  UPDATE: 'CREATE_COMPANY_UPDATE',
  CLEAR: 'CREATE_COMPANY_CLEAR',
} // createcompany

const CI_TYPE = {
  UPDATE: 'CHANGE_INFO_UPDATE',
  CLEAR: 'CHANGE_INFO_CLEAR',
} // changeinfo

const PD_TYPE = {} // pending

const DS_TYPE = {} // dissolution

const ORDER_TYPE = {
  UPDATE_CATEGORY: 'UPDATE_CATEGORY',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  TOGGLE_METHOD: 'TOGGLE_METHOD',
  UPDATE_ORDER_ID: 'UPDATE_ORDER_ID',
}

export { CC_TYPE, CI_TYPE, PD_TYPE, DS_TYPE, ORDER_TYPE }
