version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  # build_and_test:
  #   executor: node/default
  #   steps:
  #     - checkout
  #     - run: 
  #       name: Install Docker Compose
  #       environment:
  #         COMPOSE_VERSION: '3.1'
  #       command: |
  #         curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
  #         chmod +x ~/docker-compose
  #         sudo mv ~/docker-compose /usr/local/bin/docker-compose
  #     - setup_remote_docker
  #     - run: 
  #         name: Build images of services declared in docker-compose.yml
  #         command: docker-compose build
  #     - persist_to_workspace:
  #         root: ~/create-company-vite
  #         paths:
  #           - .

  deploy: # this can be any name you choose
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'a9:b8:dc:df:d6:32:fe:9c:11:66:5a:54:fc:4e:b3:ab'
      - run:
          name: pull code and start api_services
          command: ssh root@103.57.221.122 -p 24700 "cd /var/www/html/create-company-vite; docker-compose down; git pull;  docker-compose build; docker-compose up -d"

workflows:
  test_my_app:
    jobs:
      # - build_and_test
      - deploy:
          # requires:
          #   - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
