version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'a9:b8:dc:df:d6:32:fe:9c:11:66:5a:54:fc:4e:b3:ab'
      - run:
        name: Pull Code and Start Service
        command: ssh -oStrictHostKeyChecing=no root@103.57.221.122 -p 24700 "cd /var/www/html/create-company-vite; git pull; docker-compose build; docker-compose up -d"
workflows:
  cc-flows:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
