FROM node:18-alpine

WORKDIR /app

RUN apk --no-cache add bash libreoffice util-linux   font-droid-nonlatin font-droid ttf-dejavu ttf-freefont ttf-liberation

RUN apk --no-cache add msttcorefonts-installer fontconfig &&   update-ms-fonts &&   fc-cache -f

COPY backend/package.json /app/

RUN npm install --loglevel verbose

COPY backend /app/

ENV NODE_OPTIONS=--max_old_space_size=1024

ENTRYPOINT ["/bin/sh", "-c"]

EXPOSE 3001

CMD ["npm run dev"]